#if (!require("BiocManager")) install.packages("BiocManager", repos="http://cran.us.r-project.org")
#options(repos = BiocManager::repositories())
#BiocManager::install("BiocGenerics")
#if (!require("BiocGenerics")) BiocManager::install("BiocGenerics")

if (!require("devtools")) install.packages("devtools", repos="http://cran.us.r-project.org")
if (!require("shiny")) install.packages("shiny", repos="http://cran.us.r-project.org")
if (!require("shiny.info")) remotes::install_github("Appsilon/shiny.info")
#if (!require("servr")) install.packages("servr", repos="http://cran.us.r-project.org")
if (!require("ggplot2")) install.packages("ggplot2", repos="http://cran.us.r-project.org")
#if (!require("pheatmap")) install.packages("pheatmap", repos="http://cran.us.r-project.org")
if (!require("rsconnect")) install.packages("rsconnect", repos="http://cran.us.r-project.org")
#if (!require("Seurat")) install.packages("Seurat", repos="http://cran.us.r-project.org")
if (!require("patchwork")) install.packages("patchwork", repos="http://cran.us.r-project.org")
if (!require("dplyr")) install.packages("dplyr", repos="http://cran.us.r-project.org")
# if (!require("Matrix")) install.packages("Matrix", repos="http://cran.us.r-project.org")
# if (!require("tidyverse")) install.packages("tidyverse", repos="http://cran.us.r-project.org")
#if (!require("cowplot")) install.packages("cowplot", repos="http://cran.us.r-project.org")

#if (!require("reshape2")) install.packages("reshape2", repos="http://cran.us.r-project.org")
#if (!require("corrplot")) install.packages("corrplot", repos="http://cran.us.r-project.org")
#if (!require("RColorBrewer")) install.packages("RColorBrewer", repos="http://cran.us.r-project.org")
if (!require("pROC")) install.packages("pROC", repos="http://cran.us.r-project.org")
#if (!require("tidyHeatmap")) install.packages("tidyHeatmap", repos="http://cran.us.r-project.org")
# if (!require("RColorBrewer")) install.packages("RColorBrewer", repos="http://cran.us.r-project.org")
# #
# if (!require("gridExtra")) install.packages("gridExtra", repos="http://cran.us.r-project.org")
# if (!require("ggpubr")) install.packages("ggpubr", repos="http://cran.us.r-project.org")

#if(!require("ggpubr")) devtools::install_github("wjawaid/enrichR")
#if (!require("reshape2")) BiocManager::install("reshape2")
#if (!require("BiocGenerics")) BiocManager::install("reshape2")
#if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
# if (!require("ggcorrplot")) install.packages("ggcorrplot", repos="http://cran.us.r-project.org")
# if (!require("dplyr")) install.packages("dplyr", repos="http://cran.us.r-project.org")
# if (!require("tidyverse")) install.packages("cowplot", repos="http://cran.us.r-project.org")
# #if (!require("scater")) BiocManager::install("scater")


# if (!require("shinycssloaders")) install.packages("shinycssloaders", repos="http://cran.us.r-project.org")
# if (!require("shinyWidgets")) install.packages("shinyWidgets", repos="http://cran.us.r-project.org")
