---
title: "PvalueIntegration"
author: "Xin Wang"
date: "2025-04-03"
description: The script is to apply the fisher's method to collect the pvalue p1, p2, ..pk from different software and compute the text statistic: 
  
  # the current method includes protein and peptide quantification was by FragPipe.We used the MaxLFQ intensity for the DEP analyses. 
  # The DEP analyses were performed by eight pipelines

Method: Usually, the log2fold change, p value and adjusted p value are three key statistic to infer whetherh a protein is differentially expressed; Our method will integrated log2FCs and p values into a intered one. For the integration of log2FC, we choose the biggest aboslute value among all the sub-log2FC as the final one. For P value, we will apply the fisher's method to combine probablity, Similarily, Benjamini-Hochberg adusted P value will be calculated.
https://arxiv.org/pdf/1707.06897
  
    
output: html_document
---
# Loading the libraries
```{r}
#clear all the lists
rm(list=ls())
library(metap)
library(tidyverse)
library(ggplot2)
library(ggnewscale)
library(ggrepel)
#BiocManager::install("pRoloc")

library(clusterProfiler)
library(org.Hs.eg.db)
#keytypes(org.Mm.eg.db) 

library(enrichplot)
library(tidyverse)
library(factoextra)
library(purrr)

```

# set up the directory environments
```{r}

# Input directory
InputDir <- paste0("/Users/XXW004/Documents/Projects/DarylMcleod/Results/Results_03242025/Intensity_Analyses/")

# Output directory
OutDir<- paste0("/Users/XXW004/Documents/Projects/DarylMcleod/Results/Results_03242025/Intensity_Analyses/MethodIntegration/")

setwd(OutDir)


```


```{r}
# read the nine methods
# Annova
AnnavaRe <- read.csv(paste0(InputDir,"ANNOVA/", "PUV_Annovar_results_PUVvsControl.csv"))
# Limma
LimmaRe <- read.csv(paste0(InputDir,"Limma/", "PUV_Limma_results_PUVvsControl.csv"))
# DEqMS
DEqMSRe <- read.csv(paste0(InputDir,"DEqMS/", "PUV_DEqMStest_results_PUVvsControl.csv"))
# DEP
DEPRe <- read.csv(paste0(InputDir,"DEP/", "PUV_DEP_results_PUVvsControl.csv"))
# MSstats
MSstatsRe <- read.csv(paste0(InputDir,"MSstats/", "PUV_MSstats_results_PUVvsControl.csv"))
# proDA
proDARe <- read.csv(paste0(InputDir,"proDA/", "PUV_proDA_results_PUVvsControl.csv"))
# ROTS
ROTSRe <- read.csv(paste0(InputDir,"ROTS/", "PUV_ROTS_results_PUVvsControl.csv"))
# Wilcoxon
WilcoxonRe <- read.csv(paste0(InputDir,"Wilcoxon/", "PUV_Wilcoxtest_results_PUVvsControl.csv"))
# Ttest
TtestRe <- read.csv(paste0(InputDir,"Ttest/", "PUV_Ttest_results_PUVvsControl.csv"))

###### 
# we also read the protemic analyses generated by Mascot Daemon
MascotRe<- read.csv(paste0(InputDir,"Mascot_Daemon/", "FilteredProteomic_pvalue_wilcoxon3.csv"))

nrow(AnnavaRe)
nrow(LimmaRe)
nrow(DEqMSRe)
nrow(DEPRe)
nrow(MSstatsRe)
nrow(proDARe)
nrow(ROTSRe)
nrow(WilcoxonRe)
nrow(TtestRe)
nrow(MascotRe)

DEPRe %>% head()
WilcoxonRe %>% rename_with(~(paste0("Wilcoxon_",.x))) %>% dplyr::rename(ID=Wilcoxon_ID) %>% head()
MascotRe[,c(1,42:49)] %>% head()
proDARe %>% rename_with(~(paste0("proDA_",.x))) %>% dplyr::rename(ID=proDA_name) %>% head()
MascotRe[,c(1,42:49)] %>% rename_with(~(paste0("Mascot_",.x))) %>% dplyr::rename(ID=Mascot_X) %>% head()
# we rename the column name with the starting string
FinalCombinedPvalue_FC <-AnnavaRe %>% rename_with(~(paste0("Annova_",.x))) %>% dplyr::rename(ID=Annova_X) %>% inner_join(LimmaRe %>% rename_with(~(paste0("Limma_",.x))) %>% dplyr::rename(ID=Limma_X),
           by = "ID") %>% 
inner_join(DEqMSRe %>% rename_with(~(paste0("DEqMS_",.x))) %>% dplyr::rename(ID=DEqMS_X),
           by = "ID") %>% 
inner_join(proDARe %>% rename_with(~(paste0("proDA_",.x))) %>% dplyr::rename(ID=proDA_name),
           by = "ID") %>% 
inner_join(ROTSRe %>% rename_with(~(paste0("ROTS_",.x))) %>% dplyr::rename(ID=ROTS_X),
           by = "ID") %>% 
inner_join(WilcoxonRe %>% rename_with(~(paste0("Wilcoxon_",.x))) %>% dplyr::rename(ID=Wilcoxon_ID),
           by = "ID") %>% 
inner_join(TtestRe %>% rename_with(~(paste0("Ttest_",.x))) %>% dplyr::rename(ID=Ttest_X),
           by = "ID") %>%
  inner_join(DEPRe %>% rename_with(~(paste0("DEP_",.x))) %>% dplyr::rename(ID=DEP_name),
           by = "ID") %>%
inner_join(MSstatsRe %>% rename_with(~(paste0("MSstats_",.x))) %>% dplyr::rename(ID=MSstats_Gene),
          by = "ID") # we ignored the proteins that only detected in MSstats, those proteins have already removed during the filtering step in other softwares

# due to the different method and filteration of MSstat and Macot, we use the full_join and reduce function to merge multiple data frame and keep all rows from all of them. Missing data is filled with NA.
#MSstatRenameRe<- MSstatsRe %>% rename_with(~(paste0("MSstats_",.x))) %>% rename(ID=MSstats_Gene)
MascotRenameRe<- MascotRe[,c(1,42:49)] %>% rename_with(~(paste0("Mascot_",.x))) %>% dplyr::rename(ID=Mascot_X)

FinalCombinedPvalue_FC_all <-purrr::reduce(list(FinalCombinedPvalue_FC,MascotRenameRe), full_join, by ="ID")

FinalCombinedPvalue_FC_all %>% head()
nrow(FinalCombinedPvalue_FC_all)
```

# add the log2 FC, we choose the log2FC having the biggest absolute value among all the sub-logFC as the final one
```{r}
# add the log2 FC, we choose the log2FC having the biggest absolute value among all the sub-logFC as the final one

## we ignore the missing value and measure the maxium value of logFC from different software
FinalCombinedPvalue_FC_all <- FinalCombinedPvalue_FC_all %>%
  rowwise() %>%
  mutate(max_logFC = {
    vals<- c_across(c("Limma_logFC", "DEqMS_logFC","proDA_diff","ROTS_logFC","Wilcoxon_logFC","DEP_Case_vs_Controls_ratio", "MSstats_log2FC"))
    vals <- vals[is.finite(vals)] # Remove Inf, -Inf, NA
    if (all(is.na(vals))) NA else vals[which.max(abs(vals))]
  }) %>% 
  ungroup()
?all    
colnames(FinalCombinedPvalue_FC_all)
# select the colnames that contains Fold change, Pvalues, Control expression and Case expression, 
MatchedNames <- grep("ID|logFC|P\\.Value|pvalue|Wilcoxon_Case|Wilcoxon_Control",colnames(FinalCombinedPvalue_FC_all),value = TRUE)

# only select the logFC
LogFCMatchedNames <- c("ID","Limma_logFC", "DEqMS_logFC","proDA_diff","ROTS_logFC","Wilcoxon_logFC","DEP_Case_vs_Controls_ratio", "MSstats_log2FC","max_logFC")
FinalCombinedPvalue_FC_all2<-FinalCombinedPvalue_FC_all %>% dplyr::select(all_of(LogFCMatchedNames))

FinalCombinedPvalue_FC_all_TestFC <-
  FinalCombinedPvalue_FC_all %>% dplyr::select(all_of(MatchedNames))
FinalCombinedPvalue_FC_all_TestFC
write.csv(FinalCombinedPvalue_FC_all, file = "FinalCombinedPvalue_FC.csv")

```

# add the integrated P values and adjusted P values
```{r setup, include=FALSE}
# here we used the metap pacakge in R

# BiocManager::install("multtest")
# install.packages('metap')
 # Install if not already installed
library(metap)
# List of p-values
#p_values <- c(0.02, 0.05, 0.01, 0.15,0.04)

# we only select the P value as the input. The P value will be integrated by several methods: 

# PvalueRownames <- grep("P\\.Value|pvalue",colnames(FinalCombinedPvalue_FC_all), value = T)
# colnames(FinalCombinedPvalue_FC_all)
# PvalueRownames
PvalueRownames <- c("Limma_P.Value", "DEqMS_sca.P.Value","proDA_pval", "ROTS_P.Value", "Wilcoxon_P.Value","DEP_Case_vs_Controls_p.val","MSstats_pvalue","Mascot_wilpvalue")

# those are the values of the each Pvalues
FinalCombinedPvalue_FC_all[,PvalueRownames] %>% head()

TestPvalue<- FinalCombinedPvalue_FC_all %>% dplyr::select(PvalueRownames) %>% as.data.frame()
 rownames(TestPvalue) <- FinalCombinedPvalue_FC_all$ID
TestPvalue %>% head()
# we thought the method might not be independent, therefore we use permuation based integration
library(metap)

TestPvalue$FinalP_empirical <- apply(TestPvalue[,PvalueRownames], 1, function(x) {
  # orginal fisher statistic
  pvals <- x[!is.na(x)]
  observed <- sum(-2 * log(pvals))
  # Permute: simulate under null (uniform p-values)
  set.seed(123)
  n_perm <- 100000
  perm_stats <- replicate(n_perm, sum(-2 * log(runif(length(pvals)))))
  
  # Empirical p-value
  empirical_p <- mean(perm_stats >= observed)
  return(empirical_p)
})
# Apply Fisher’s method
TestPvalue$FinalP_Fisher<- apply(TestPvalue[,PvalueRownames], 1, function(x) sumlog(x[!is.na(x)])$p)

# Apply Tippett’s Method (For Highly Sensitive Detection)
TestPvalue$FinalP_Tippett<- apply(TestPvalue[,PvalueRownames], 1, function(x) 1 - (1 - min(x[!is.na(x)]))^length(x[!is.na(x)]))
# Apply stouffer's Z score method:

TestPvalue$FinalP_Stouffer<- apply(TestPvalue[,PvalueRownames], 1, function(x) sumz(x[!is.na(x)])$p)

# add the adjusted P value using Bo
TestPvalue$FinaladjP_Fisher<- p.adjust(TestPvalue$FinalP_Fisher,method = "BH")
TestPvalue$FinaladjP_Tippett<- p.adjust(TestPvalue$FinalP_Tippett,method = "BH")
TestPvalue$FinaladjP_Stouffer <- p.adjust(TestPvalue$FinalP_Stouffer, method = "BH")
TestPvalue$FinaladjP_empirical <- p.adjust(TestPvalue$FinalP_empirical, method = "BH")
# TestPvalue$FinalP <- apply(TestPvalue, 1, function(x) {
#   valid_x <- x[!is.na(x) & x > 0 & x <= 1]
#   if (length(valid_x) >= 2) {
#     res <- sumlog(valid_x)$p
#   } else {
#     res <- NA  # or some fallback
#   }
#   return(res)
# })
TestPvalue %>% filter(FinaladjP_empirical <=0.05) %>% nrow()
TestPvalue %>% filter(FinaladjP_Stouffer <=0.05) %>% nrow()
TestPvalue %>% filter(FinaladjP_Tippett <=0.05) %>% nrow()
TestPvalue %>% filter(FinaladjP_Fisher <=0.05) %>% nrow()

TestPvalue %>% filter(FinalP_empirical <=0.05) %>% nrow()
TestPvalue %>% filter(FinalP_Stouffer <=0.05) %>% nrow()
TestPvalue %>% filter(FinalP_Fisher <=0.05) %>% nrow()
TestPvalue %>% filter(FinalP_Tippett <=0.05) %>% nrow()
# save final P values
FinalCombinedPvalue_FC_all %>% head()
TestPvalue %>% rownames_to_column("ID") %>% head()
FinalCombinedPvalue_FC_all_final<- FinalCombinedPvalue_FC_all %>% inner_join(TestPvalue %>% rownames_to_column("ID"),by ="ID") %>% arrange(FinalP_Fisher)
#FinalCombinedPvalue_FC_all_final %>% arrange(FinalP_Fisher)
write.csv(FinalCombinedPvalue_FC_all_final, file = "FinalCombinedPvalue_IntegratedMethods.csv")
# select the colnames that contains Fold change, Pvalues, Control expression and Case expression, 
FMatchedNames <- grep("ID|logFC|P\\.Value|pvalue|Wilcoxon_Case|Wilcoxon_Control|FinalP|FinaladjP",colnames(FinalCombinedPvalue_FC_all_final),value = TRUE)
FMatchedNames
FinalCombinedPvalue_FC_all_TestFC <-
  FinalCombinedPvalue_FC_all_final %>% dplyr::select(all_of(rev(FMatchedNames))) %>% arrange(FinaladjP_Stouffer)
FinalCombinedPvalue_FC_all_TestFC %>% head()
#write.csv(FinalCombinedPvalue_FC_all, file = "FinalCombinedPvalue_FC.csv")

```
